#pragma once

#include "data.h"
#include <math.h>
#include <pebble.h>

static inline float get_scale_factor(void)
{
#ifdef PBL_PLATFORM_EMERY
    return 1.35f;
#else
    return 1.0f;
#endif
}

#define PLATFORM_SCALE(x) ((int16_t)ceilf((x) * get_scale_factor()))

// Base dimensions based on 144x168
#define DRAWING_STROKE_BASE 3
#define DRAWING_SIZE_BASE 30
#define PADDING_BASE 6
#define CORNER_RADIUS_MAIN_BASE 14
#define CORNER_RADIUS_BUBBLE_BASE 8
#define REGION_BUBBLE_WIDTH_BASE 54
#define REGION_BUBBLE_HEIGHT_BASE 20
#define SCORE_BUBBLE_WIDTH_BASE 48
#define SCORE_BUBBLE_HEIGHT_BASE 34
#define TIME_BUBBLE_HEIGHT_BASE 62
#define LOADING_TEXT_Y_PADDING_BASE 50
#define LOADING_TEXT_HEIGHT_BASE 30

// Scaled dimensions
#define DRAWING_STROKE PLATFORM_SCALE(DRAWING_STROKE_BASE)
#define DRAWING_SIZE PLATFORM_SCALE(DRAWING_SIZE_BASE)
#define PADDING PLATFORM_SCALE(PADDING_BASE)
#define CORNER_RADIUS_MAIN PLATFORM_SCALE(CORNER_RADIUS_MAIN_BASE)
#define CORNER_RADIUS_BUBBLE PLATFORM_SCALE(CORNER_RADIUS_BUBBLE_BASE)
#define REGION_BUBBLE_WIDTH PLATFORM_SCALE(REGION_BUBBLE_WIDTH_BASE)
#define REGION_BUBBLE_HEIGHT PLATFORM_SCALE(REGION_BUBBLE_HEIGHT_BASE)
#define SCORE_BUBBLE_WIDTH PLATFORM_SCALE(SCORE_BUBBLE_WIDTH_BASE)
#define SCORE_BUBBLE_HEIGHT PLATFORM_SCALE(SCORE_BUBBLE_HEIGHT_BASE)
#define TIME_BUBBLE_HEIGHT PLATFORM_SCALE(TIME_BUBBLE_HEIGHT_BASE)
#define LOADING_TEXT_Y_PADDING PLATFORM_SCALE(LOADING_TEXT_Y_PADDING_BASE)
#define LOADING_TEXT_HEIGHT PLATFORM_SCALE(LOADING_TEXT_HEIGHT_BASE)

// Font selection based on platform
#ifdef PBL_PLATFORM_EMERY
#define LABEL_FONT FONT_KEY_GOTHIC_18_BOLD
#define DATE_FONT FONT_KEY_GOTHIC_18_BOLD
#define LOADING_FONT FONT_KEY_GOTHIC_24_BOLD
#else
#define LABEL_FONT FONT_KEY_GOTHIC_14_BOLD
#define DATE_FONT FONT_KEY_GOTHIC_14_BOLD
#define LOADING_FONT FONT_KEY_GOTHIC_18_BOLD
#endif

void ui_init(void);
void ui_deinit(void);
void update_all(void);
void update_score(TimePeriod time);
void draw_score_bubble(GContext *ctx, Layer *layer, TimePeriod time);
void show_main_window(void);
